version: '3.4'

services:
  elang.api:
    image: local/elang-api
    container_name: elang.api
    build:
      context: .
      dockerfile: src/Elang.Api/Dockerfile
    ports:
      - "5000:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ConnectionStrings__Default=User ID=admin;Password=admin;Host=host.docker.internal;Port=5432;Database=elangDb;Connection Lifetime=0;
